/** @type {import('tailwindcss').Config} */
module.exports = {
  darkMode: 'class',
  content: ['./index.html', './src/**/*.{vue,js,ts,jsx,tsx}'],
  theme: {
    extend: {
      colors: {
        'surface-container-lowest': '#070b14',
        'surface-container-low': '#0a0f1e',
        'surface-container': '#0d1626',
        'surface-container-high': '#111e32',
        'surface-container-highest': '#182840',
        'surface-dim': '#0a0f1e',
        surface: '#0d1626',
        'surface-bright': '#1e3050',
        'surface-variant': '#182840',
        background: '#0a0f1e',
        'on-surface': '#e8f4ff',
        'on-surface-variant': '#7eaac8',
        'on-background': '#e8f4ff',
        'inverse-surface': '#e8f4ff',
        'inverse-on-surface': '#0d1626',
        outline: '#2e5a7a',
        'outline-variant': '#162038',
        'surface-tint': '#00d2ff',
        primary: '#e8f4ff',
        'on-primary': '#001a2e',
        'primary-container': '#00d2ff',
        'on-primary-container': '#001a2e',
        'inverse-primary': '#0066aa',
        'primary-fixed': '#7de8ff',
        'primary-fixed-dim': '#00d2ff',
        'on-primary-fixed': '#001a2e',
        'on-primary-fixed-variant': '#004466',
        secondary: '#93bfff',
        'on-secondary': '#001a50',
        'secondary-container': '#0066ff',
        'on-secondary-container': '#d0e8ff',
        'secondary-fixed': '#b8d8ff',
        'secondary-fixed-dim': '#93bfff',
        'on-secondary-fixed': '#001040',
        'on-secondary-fixed-variant': '#003388',
        tertiary: '#f0f8ff',
        'on-tertiary': '#001a3a',
        'tertiary-container': '#4db8ff',
        'on-tertiary-container': '#001a30',
        'tertiary-fixed': '#c8e8ff',
        'tertiary-fixed-dim': '#4db8ff',
        'on-tertiary-fixed': '#001020',
        'on-tertiary-fixed-variant': '#002255',
        error: '#ffb4ab',
        'on-error': '#690005',
        'error-container': '#93000a',
        'on-error-container': '#ffdad6',
      },
      fontFamily: {
        sans: ['Inter', 'sans-serif'],
        inter: ['Inter', 'sans-serif'],
      },
      fontSize: {
        'display-xl': ['48px', { lineHeight: '1.1', letterSpacing: '-0.04em', fontWeight: '800' }],
        'headline-lg': ['32px', { lineHeight: '1.2', letterSpacing: '-0.02em', fontWeight: '700' }],
        'headline-md': ['24px', { lineHeight: '1.3', fontWeight: '600' }],
        'body-lg': ['18px', { lineHeight: '1.6', fontWeight: '400' }],
        'body-md': ['16px', { lineHeight: '1.6', fontWeight: '400' }],
        'label-sm': ['12px', { lineHeight: '1.0', letterSpacing: '0.05em', fontWeight: '600' }],
      },
      borderRadius: {
        sm: '0.25rem',
        DEFAULT: '0.5rem',
        md: '0.75rem',
        lg: '1rem',
        xl: '1.5rem',
        '2xl': '1.5rem',
        '3xl': '2rem',
        full: '9999px',
      },
      spacing: {
        unit: '8px',
        'gutter-md': '24px',
        'margin-edge': '40px',
        'container-max': '1440px',
      },
      boxShadow: {
        'cyan-glow-sm': '0 0 10px rgba(0, 210, 255, 0.8)',
        'cyan-glow-md': '0 0 30px rgba(0, 210, 255, 0.4)',
        'cyan-glow-lg': '0 0 100px rgba(0, 210, 255, 0.08)',
        'blue-glow-md': '0 0 30px rgba(0, 102, 255, 0.4)',
        'blue-glow-lg': '0 0 60px rgba(0, 102, 255, 0.2)',
        'player-top': '0 -10px 50px rgba(0, 0, 0, 0.6)',
        'header-glow': '0 0 40px -15px rgba(0, 210, 255, 0.25)',
        'ambient-card': '0 0 100px 0 rgba(0, 210, 255, 0.06)',
        'glass-inset': 'inset 0 1px 0 rgba(255, 255, 255, 0.12)',
        'liquid-border': 'inset 0 0 20px rgba(255, 255, 255, 0.04)',
        'ambient-album': '0 0 100px rgba(0, 210, 255, 0.2)',
      },
      backdropBlur: {
        glass: '40px',
        'glass-deep': '60px',
        'glass-heavy': '80px',
      },
      animation: {
        slideup: 'slideup 1s ease-in-out',
        slidedown: 'slidedown 1s ease-in-out',
        slideleft: 'slideleft 1s ease-in-out',
        slideright: 'slideright 1s ease-in-out',
        wave: 'wave 1.2s linear infinite',
        slowfade: 'slowfade 2.2s ease-in-out',
        'spin-slow': 'spin 10s linear infinite',
        'pulse-glow': 'pulse-glow 3s ease-in-out infinite',
        float: 'float 6s ease-in-out infinite',
      },
      keyframes: {
        slowfade: { from: { opacity: 0 }, to: { opacity: 1 } },
        slideup: { from: { opacity: 0, transform: 'translateY(25%)' }, to: { opacity: 1, transform: 'none' } },
        slidedown: { from: { opacity: 0, transform: 'translateY(-25%)' }, to: { opacity: 1, transform: 'none' } },
        slideleft: { from: { opacity: 0, transform: 'translateX(-20px)' }, to: { opacity: 1, transform: 'translateX(0)' } },
        slideright: { from: { opacity: 0, transform: 'translateX(20px)' }, to: { opacity: 1, transform: 'translateX(0)' } },
        wave: { '0%': { transform: 'scale(0)' }, '50%': { transform: 'scale(1)' }, '100%': { transform: 'scale(0)' } },
        'pulse-glow': {
          '0%, 100%': { opacity: '0.12' },
          '50%': { opacity: '0.22' },
        },
        float: {
          '0%, 100%': { transform: 'translateY(0px)' },
          '50%': { transform: 'translateY(-8px)' },
        },
      },
    },
  },
  plugins: [],
};
